-- Entrées d'argent hors factures : apports personnels, subsides,
-- remboursements… Les ventes restent dans la table factures.
-- Mêmes colonnes et mêmes droits que depenses (page Gestion).
create table if not exists public.entrees (
  id           bigint generated by default as identity primary key,
  date         date not null default current_date,
  libelle      text not null,
  montant      numeric not null check (montant > 0),
  categorie    text not null default 'apport',
  fournisseur  text,
  notes        text,
  justificatif text,
  created_at   timestamptz default now()
);

alter table public.entrees enable row level security;

drop policy if exists entrees_lire on public.entrees;
drop policy if exists entrees_creer on public.entrees;
drop policy if exists entrees_modifier on public.entrees;
drop policy if exists entrees_supprimer on public.entrees;

create policy entrees_lire      on public.entrees for select to authenticated using (public.a_acces(array['gestion']));
create policy entrees_creer     on public.entrees for insert to authenticated with check (public.peut_ecrire(array['gestion']));
create policy entrees_modifier  on public.entrees for update to authenticated using (public.peut_ecrire(array['gestion'])) with check (public.peut_ecrire(array['gestion']));
create policy entrees_supprimer on public.entrees for delete to authenticated using (public.peut_effacer(array['gestion']));

grant select, insert, update, delete on public.entrees to authenticated;
