-- La colonne depenses.id n'avait ni séquence ni identité : une insertion
-- sans id depuis l'ERP (Gestion › Dépenses) échouait. On la passe en
-- identité, en repartant après le plus grand id existant.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='depenses' and column_name='id' and is_identity='YES'
  ) then
    alter table public.depenses alter column id add generated by default as identity;
  end if;
end $$;

select setval(
  pg_get_serial_sequence('public.depenses','id'),
  coalesce((select max(id) from public.depenses),0)+1,
  false
);
